apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-pss
  namespace: pss-test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: ["/bin/bash"]
    args: ["-c", "sleep 3600"]
    securityContext:
      privileged: false